POST http://127.0.0.1:1903/shorten
Content-Type: application/json

{
  "url": "https://www.google.com"
}

###

PUT http://127.0.0.1:1903/shorten/zcxfJH
Content-Type: application/json

{
  "url": "https://www.movie.com"
}